apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webtravel-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Lghthien/infrastructure.git
    targetRevision: main
    path: "k8s/travel_web_deploys"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
