apiVersion: v1
kind: Service
metadata:
  name: backend-service-nodeport
  namespace: default
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31000
