apiVersion: v1
kind: Service
metadata:
  name: frontend-service-nodeport
  namespace: default
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000 # phải trong 30000-32767 (ví dụ 31000)
